### ISSUE TITLE
upgrade

### ISSUE THREAD

**Issue by dpertal** [tovic/nextprev-plugin-for-morfy-cms#1]
Hi tovic,
maybe you can upgrade to be compatible for morfy version 1.1.2;
thanks

**Comment by taufik-nurrohman** [comment]
On the way&hellip;

**Comment by dpertal** [comment]
release date;
thanks

**Comment by taufik-nurrohman** [comment]
Try the master version.

https://github.com/tovic/nextprev-plugin-for-morfy-cms/commit/5d8ad7f2bac9a039fb457a148103617564fa8401
