### ISSUE TITLE
upgrade plugin for morfy 2.X.X

### ISSUE THREAD

**Issue by dpertal** [tovic/nextprev-plugin-for-morfy-cms#3]
hi

you must upgrade the plugin! http://morfy.org/blog/morfy-2.0.0

**Comment by taufik-nurrohman** [comment]
@dpertal The development [still running](https://github.com/morfy-cms/morfy/commits/dev) just after the release of `2.0.0`. So I think I will update it on the next release.

**Comment by Awilum** [comment]
@tovic 2.0.0 is stable and I have no plan to publish 3.0.0 with totaly new API in near future. So thats mean that Morfy 2 will have such API as is for long time, half or a year at least.

**Comment by Awilum** [comment]
next Morfy release will be - 2.0.1 with small bug fixes.

**Comment by taufik-nurrohman** [comment]
OK then. I need a time.
